FROM node:8.9.4-alpine
MAINTAINER Chunghee park <dev.roy.park@gmail.com>

WORKDIR /app
RUN    apk update
RUN    apk upgrade
RUN    apk add imagemagick imagemagick-dev

ADD    media/start-dev.sh         /start-dev.sh
RUN    chmod +x /*.sh
